name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run your Node.js script
      - name: Run index.js
        run: npm start

      # 5️⃣ Run tests
      - name: Run tests
        run: npm test
